# Site settings
author: Emily Xi
title: Ems_Codes
header-img: img/home-bg.png
email: emilyxi@gmail.com
copyright_name: Emily Xi
description: > # this means to ignore newlines until "baseurl:"
  Newbie Coder
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Ems-codes

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
